version: "2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  consul:
    image: consul
    command: [agent, -server, -bootstrap, -client=0.0.0.0, -ui]
    networks:
      app_net:
        ipv4_address: 172.16.13.200
    ports:
      - "8500:8500"
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
  ui:
    image: node:6-alpine
    volumes:
          - ./ui:/usr/src/app
    entrypoint: sh -c "cd /usr/src/app && npm start"
    ports:
      - "8080:8080"
  user-service:
    image: kodingklub/user-service
    depends_on:
      - db
      - consul
    networks:
      - default
      - app_net

networks:
  app_net:
    ipam:
      driver: default
      config:
      - subnet: 172.16.13.0/24
        gateway: 172.16.13.1